### ISSUE TITLE
Create home page, user guide, and API docs as our custom websites (not via GitHub wiki)

### ISSUE THREAD

**Issue by kagikn** [scripthookvdotnet/scripthookvdotnet#1235]
So we can provide decent quality and amount of info of SHVDN more effectively. Well, look at the home pages of [FiveM](https://fivem.net), [RPH](https://ragepluginhook.net), or those of other libraries or frameworks such as [React](https://react.dev) and [Laravel](https://laravel.com), they provide a lot of info with their home pages with rich visual.
If we need to use our own domain(s) later, we can redirect our github.io websites to them (e.g. Mapbox and PyTorch).

# Tasks
- [x] Create home page
- [ ] Create user guide with custom website
- [ ] Create API docs

# Home Page Prototype
<img src="https://github.com/scripthookvdotnet/scripthookvdotnet/assets/9353978/0137b6ca-a146-4ea8-bd76-9824e022ea60">

Used elements: Open Sans (same as the body font family in the home page of .NET), background-color "222129", and a .NET Framework-ish blue color "00AFEA".
I'm not using .NET purple as the primary color since Microsoft started using purple for .NET logo since .NET 4.6, and SHVDN initally used .NET Framework 4.5.2. I'd like to keep the purple (as a primary theme color) until we create a new .NET runtime for .NET 7+. I'm a fan of dark themes rather than light ones, and I'm using a dark(-ish) theme for the home page as well as FiveM.

**Comment by kagikn** [comment]
Okay, made the home page. Kinda rough but decent enough to me as a PoC. https://scripthookvdotnet.github.io

**Comment by BoBoBaSs84** [comment]
A Time Machine... Out Of A DeLorean?
